DOMAIN = "binance"
PLATFORMS = ["sensor"]
CONF_API_KEY = "API_KEY"
CONF_API_SECRET = "API_SECRET"
CONF_PAIRS = "PAIRS"
CONF_MARKET_TYPE = "MARKET"
CONF_FUTURES_PAIRS = "FUTURES PAIRS"
CONF_SPOT_PAIRS = "SPOT PAIRS"
